# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: jilaikeji@163.com
brand: 来宝
headline: 玩游戏，得奖励
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 备案号:京ICP备19050671号

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: jilaikeji@163.com

# Tracking
googleAnalitycsID: UA-83933844-1

